### ISSUE TITLE
Post Wobbrock Readings

### ISSUE THREAD

**Issue by annie-r** [uwcse510/web-cse510-sp17#22]
After I create a template for the days where I'm assigning readings, please post Benko's selected readings:

> For human performance, I’d try to choose among these readings. The first seems mandatory.
>  
> Basic:
> I. S. MacKenzie. 1992. Fitts’ law as a research and design tool in human-computer interaction. Human-Computer Interaction 7, 1: 91–139. http://www.yorku.ca/mack/HCI.html
>  
> J. Accot and S. Zhai. 1997. Beyond Fitts’ law: Models for trajectory-based HCI tasks. In Proceedings of the ACM Conference on Human Factors in Computing Systems (CHI ’97), 295–302. https://doi.org/10.1145/258549.258760.
>  
> Jacob Otto Wobbrock, Edward Cutrell, Susumu Harada, and I. S. MacKenzie. 2008. An error model for pointing based on Fitts’ law. In Proceedings of the ACM Conference on Human Factors in Computing Systems (CHI ’08), 1613–1622. https://doi.org/10.1145/1357054.1357306.
>  
>  
> Applied:
> I. S. MacKenzie, T. Kauppinen, and M. Silfverberg. 2001. Accuracy measures for evaluating computer pointing devices. In Proceedings of the ACM Conference on Human Factors in Computing Systems (CHI ’01), 9–16. https://doi.org/10.1145/365024.365028.
>  
> Georg Apitz and François Guimbretière. 2004. CrossY: A crossing-based drawing application. In Proceedings of the ACM Symposium on User Interface Software and Technology (UIST ’04), 3–12. https://doi.org/10.1145/1029632.1029635

**Comment by jayfo** [comment]
Later in that email, Jake and I agreed MacKenzie 1992 is the framing paper, the two applied papers are the "pick 1 to read" papers, and we'll list the other 2 papers as additional resources.
