### ISSUE TITLE
Linkify Christian's Readings

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-sp17#60]

**Comment by annie-r** [comment]
which would be...

**Comment by jayfo** [comment]
They are on the calendar, but they don't currently link to PDFs.

**Comment by annie-r** [comment]
do you have the book chaper 7 Bill Buxton. Touch, Gesture, & Marking. Book chapter 7 in Ronald M. Baecker, Jonathan Grudin, Bill Buxton, and Saul Greenberg, Readings in Human-Computer Interaction: Toward the Year 2000 I can't find the full text online in any easily accessible location

**Comment by annie-r** [comment]
else, it looks like the library has the physical book. I can go scan the chapter

**Comment by jayfo** [comment]
I found it linked from the 16wi offering.  It's just a website:

http://billbuxton.com/MKhaptic.html

But I made a PDF to be more "robust".  Attached.

[Buxton_TouchGestureMarking.pdf](https://github.com/uwcse510/web-cse510-sp17/files/944833/Buxton_TouchGestureMarking.pdf)
